### ISSUE TITLE
Omeka S 4.0.1 

### ISSUE THREAD

**Issue by yaeln** [biblibre/omeka-s-module-ItemSetCalendar#2]
Hi,
I have again a 'beginner's question' - as this module is so very useful to us, but I am not a developer  - concerning the update of the module to Omeka S 4.0.1 - is there a general way to update the version so it will work now?
Thanks very much in advance.
Yael

**Comment by jajm** [comment]
Hi,

In theory, all you need to do is modify the file `config/module.ini` and replace the line:

```
omeka_version_constraint = "^3.0.0"
```

by

```
omeka_version_constraint = "^3.0.0 || ^4.0.0"
```

But I haven't tested it. Please let me know if the module work with Omeka S 4 and I will do a proper release.

**Comment by yaeln** [comment]
Seems to be fine!
There is a warning, but it may be my fault

Warning: Undefined variable $pageTitle in /home/evaanita/public_html/ehud/modules/ItemSetCalendar/view/item-set-calendar/site/item/browse.phtml on line 12

**Comment by jajm** [comment]
v0.3.0 is released and is compatible with Omeka 4.x

Thank you for testing!

**Comment by yaeln** [comment]
Thanks a lot!
